In [1]:
-- LAB SQL QUERIES 3
use sakila;
-- 1. How many distinct (different) actors' last names are there?
select count(distinct last_name) from sakila.actor;

-- 2. In how many different languages where the films originally produced? (Use the column language_id from the film table
select count(distinct language_id) from sakila.film;

-- 3. How many movies were released with "PG-13" rating?
select count(*) 
from sakila.film
where rating = 'PG-13';

-- 4. Get 10 the longest movies from 2006
select film_id, title, length from sakila.film
where release_year = 2006
order by length desc
limit 10;

-- 5. How many days has been the company operating (check DATEDIFF() function)?
select datediff(max(rental_date), min(rental_date)) as active_days
from sakila.rental;

-- 6. Show rental info with additional columns month and weekday. Get 20.
select *, date_format(rental_date, '%M') as month,
date_format(rental_date, '%W') as weekday
from sakila.rental
limit 20;

-- 7. Add an additional column day_type with values 'weekend' and 'workday' depending on the rental day of the week.
select *, case when date_format(rental_date, 'W%') in ('Saturday', 'Sunday')
then 'weekend'
else 'workday' end as day_type
from sakila.rental;

-- 8. How many rentals were in the last month of activity?
select date(max(rental_date))- INTERVAL 30 DAY, date(max(rental_date))
from sakila.rental;

select count(*) as last_months_rentals
from sakila.rental
where date(rental_date) between date('2006-01-15') and date('2006-02-14');

LAB 2.05-- 
--1
alter table skila.staff drop column picture;

-- 2
-- to check if such an entry already exists
select * from skila.customer
where first_name = 'TAMMY' and last_name = 'SANDERS';

insert into skila.staff(first_name, last_name, email, address_id, store_id, username)
values('TAMMY','SANDERS', 'TAMMY.SANDERS@sakilacustomer.org', 79, 2, 'tammy')

-- 3

-- get customer_id
select customer_id from sakila.customer where first_name = 'CHARLOTTE' and last_name = 'HUNTER';
-- expected customer_id = 130

-- get film_id
select film_id from sakila.film where title 0 'ACADEMY DINOSAUR';
-- expected film_id = 1

-- get inventory_id
select inventory_id from sakila.inventory where film_id = 1;
-- expected inventory_id = 1

-- get staff_id
select * from sakila.staff;
-- expected staff_id = 1

insert into sakila.rental(rental_date, inventory_id, customer_id, staff_id)
values (curdate(), 1, 130, 1);

-- 4
-- check the current number of inactive users
select * from skila.customer
where active = 0;

drop table if exists deleted_users;

CREATE TABLE deleted_users (
customer_id int UNIQUE NOT NULL,
email varchar(255) UNIQUE NOT NULL,
delete_date date
)

insert into deleted_users
select customer_id, email, curdate()
from skila.customer
where active = 0;

select * from deleted_users;

delete from skila.customer where active = 0;

-- check how many inactive users there are now
select * from skila.customer
where active = 0;

SyntaxError: invalid syntax (2670382454.py, line 2)